# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HrWknxteH3pik6ioqVwImK2px3NrnXgg
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv('glints_jobs_clean.csv')

# Cek informasi dasar untuk menjawab tugas preprocessing Pekan 1
print(df.info())
df.head()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load dataset
df = pd.read_csv('glints_jobs_clean.csv')

# 2. FEATURE ENGINEERING
# Menghitung Gaji Rata-rata dari kolom yang sudah ada di filemu
# Kita abaikan data yang isinya "Tidak ada" agar bisa dihitung secara matematis
df['Gaji_Min_Clean'] = pd.to_numeric(df['Gaji_Min'], errors='coerce')
df['Gaji_Max_Clean'] = pd.to_numeric(df['Gaji_Max'], errors='coerce')
df['Gaji_Rata_Rata'] = (df['Gaji_Min_Clean'] + df['Gaji_Max_Clean']) / 2

# 3. EDA - 10 Keterampilan Paling Dicari (Menjawab Pertanyaan Bisnis 1)
plt.figure(figsize=(12, 6))
# Kolom di filemu namanya 'Skills'
skills_series = df['Skills'].dropna().str.split(',').explode().str.strip()
top_skills = skills_series.value_counts().head(10)

sns.barplot(x=top_skills.values, y=top_skills.index, palette='viridis')
plt.title('10 Keterampilan Paling Dicari (Analisis CareerSync)')
plt.xlabel('Jumlah Lowongan')
plt.ylabel('Keterampilan')
plt.show()

# 4. EDA - Distribusi Gaji Berdasarkan Kota (Menjawab Pertanyaan Bisnis 3)
plt.figure(figsize=(12, 6))
# Kolom di filemu namanya 'Kota'
top_cities = df['Kota'].value_counts().head(5).index
df_top_cities = df[df['Kota'].isin(top_cities)].copy()

sns.boxplot(data=df_top_cities, x='Kota', y='Gaji_Rata_Rata')
plt.title('Rentang Gaji di 5 Kota Terbanyak')
plt.ylabel('Gaji Rata-Rata (IDR)')
plt.xlabel('Kota')
plt.show()

# 5. Tampilkan ringkasan singkat untuk laporanmu
print(f"Total data yang dianalisis: {len(df)} lowongan")
print(f"Keterampilan nomor 1 yang paling dicari adalah: {top_skills.index[0]}")

# Simpan ke CSV baru untuk diserahkan ke tim AI
df.to_csv('glints_cleaned_for_model.csv', index=False)
print("File glints_cleaned_for_model.csv berhasil dibuat!")